#:schema node_modules/wrangler/config-schema.json
name = "stream-test"
compatibility_date = "2024-05-12"
pages_build_output_dir = "./build/client"




[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "stream-test"
database_id = "5871b3a1-2851-46e2-88bd-af65d3a3c872"

[placement]
mode = "off"